#!/bin/sh
# Get the committer's name
committer_name=$(git log -1 --pretty=%an)

# Run commitlint to validate commit message format
npx --no-install commitlint --edit $1

# Check if commitlint failed
if [ $? -ne 0 ]; then
  echo "Hey $committer_name, your commit message does not follow the required format."
  
  # Custom error messages based on your rules
  echo "Here are the rules you need to follow:"
  echo "1. The commit header (first line) should be a maximum of 72 characters."
  echo "2. The commit type must be one of the following: feat, fix, docs, style, refactor, test, chore."
  echo "3. The subject (the commit message) should not use Start Case or Pascal Case."
  echo "4. The commit type must be in lowercase."

  echo "Please fix these issues and try again."

  exit 1
fi
